### Home page
http://localhost:8080/books

### Test 1: Get contents of a database
GET http://localhost:8080/books

### View all books
http://localhost:8080/viewall

### Test 2: Sign up and log in
http://localhost:8080/signup?username=patrick&password=project

###
http://localhost:8080/login?username=patrick&password=project


### Test 3: Post book records
POST http://localhost:8080/books

{"Title":"The Lord of the Rings: Fellowship of the Ring", "Author":"JR Tolkien", "BookType":"Novel", "Genre":"Fantasy, Adventure","Rating":"","Status":"Wish List","Notes":""}
###
POST http://localhost:8080/books

{"Title":"The Knife of Never Letting Go", "Author":"Patrick Ness", "BookType":"Novel", "Genre":"Young-Adult, Science Fiction","Rating":"10","Status":"Finished","Notes":"Brilliant!"}
###
POST http://localhost:8080/books

{"Title":"The Mysterious Benedict Society", "Author":"Trenton Lee Stewart", "BookType":"Novel", "Genre":"Young-Adult, Adventure","Rating":"10","Status":"Finished","Notes":"Easy read, smart writing"}
###
POST http://localhost:8080/books

{"Title":"The Catcher in the Rye", "Author":"J.D. Salinger", "BookType":"Novel", "Genre":"Fiction","Rating":"7","Status":"Finished","Notes":"Thought provoking, a bit slow"}
###
POST http://localhost:8080/books

{"Title":"The Shadow of Kyoshi", "Author":"F.C. Yee", "BookType":"Novel", "Genre":"Science Fiction, Adventure","Rating":"","Status":"Ongoing","Notes":"Great so far"}
###
POST http://localhost:8080/books

{"Title":"The Rise of Kyoshi", "Author":"F.C. Yee", "BookType":"Novel", "Genre":"Science Fiction, Adventure","Rating":"10","Status":"Finished","Notes":"Incredible"}


### Test 4: Filter book entries
http://localhost:8080/filterbyrating?rating=10

### 
http://localhost:8080/filterbybooktype?booktype=Novel


### Test 5: Delete a book entry
DELETE http://localhost:8080/books/1

### Test 6: Update a book entry
PUT http://localhost:8080/books/2?notes=Loved it

### Test 7: Log out of user
http://localhost:8080/logout

### Test 8: Sign up and login for another user

http://localhost:8080/signup?username=user2&password=user2

###
http://localhost:8080/login?username=user2&password=user2


### Test 9: Create, add to, add members and access a new group
http://localhost:8080/newgroup?groupname=bookclub

###
http://localhost:8080/addtogroup?groupname=bookclub&title=The Lord of the Rings: Fellowship of the Ring

###
http://localhost:8080/addtogroup?groupname=bookclub&title=The Shadow of Kyoshi

###
http://localhost:8080/addgroupmember?groupname=bookclub&member=patrick

###
http://localhost:8080/viewgroup?groupname=bookclub


### Test 10: Recommend a book to another user and save recommendations into personal database
http://localhost:8080/recommend?username=patrick&bookname=The Shadow of Kyoshi

###
http://localhost:8080/addrecs
